#!/bin/bash

case "$2" in
  up)
    systemctl start tor.service
    ;;
  vpn-up)
    systemctl start tor.service
    ;;
  down)
    systemctl stop tor.service
    ;;
  vpn-down)
    systemctl stop tor.service
    ;;
esac
